In [4]:
import numpy as np

作業目標<br>
讀取存取陣列資料<br>
作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [5]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

with open('one_array.npy', 'wb') as f:
    np.save(f, array1)
with open('two_array.npy', 'wb') as f:
    np.save(f, array2)

In [10]:

a1 = np.load('one_array.npy')
a2 = np.load('two_array.npy')
a3 = np.load('multi_array.npz')
a4 = np.genfromtxt("names.txt", delimiter=",", names=True)
a5 = np.genfromtxt('test.csv', delimiter=",")
a6 = np.genfromtxt('test.gz', delimiter=",")
a7 = np.load('test.npy')
a8 = np.genfromtxt('test.out', delimiter="#")
a9 = np.genfromtxt("transform.txt", delimiter=',', dtype="i8, i8, U3, U3")


In [11]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
a2

array([2, 3, 5])

In [13]:
a3

In [14]:
a4

array([(1., 2., 3.), (4., 5., 6.), (7., 8., 9.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [15]:
a5

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [16]:
a6

array([0., 1., 2., 3., 4.])

In [17]:
a7

array([1, 2], dtype=int64)

In [18]:
a8

array([0., 1., 2., 3., 4.])

In [19]:
a9

array([(1, 2, 'Yes', '87%'), (3, 4, 'No', '3%'), (5, 6, 'Yes', '55%')],
      dtype=[('f0', '<i8'), ('f1', '<i8'), ('f2', '<U3'), ('f3', '<U3')])